-- SPDX-License-Identifier: MIT

import Basic.Semantics

/-!
The equational theory generated by a conjunction's equality literals. The
inductive derivation relation closes assumptions under equivalence and function
congruence, with a proof that every derivation is semantically sound.
-/

namespace EUF

/-- Equality derivations generated by input equalities and congruence.

This relation ranges over all ground terms, not merely the finitely many terms
occurring in `cube`. It is the equational theory induced by the equality
literals of `cube`. -/
inductive DerivesEq (formula : Cube σ) : Term σ → Term σ → Prop where
  | refl (term) : DerivesEq formula term term
  | assumption {left right} :
      Literal.eq left right ∈ formula → DerivesEq formula left right
  | symm {left right} :
      DerivesEq formula left right → DerivesEq formula right left
  | trans {left middle right} :
      DerivesEq formula left middle →
      DerivesEq formula middle right →
      DerivesEq formula left right
  | congr {arity} (function : σ.Function arity) {leftArgs rightArgs} :
      (∀ i, DerivesEq formula (leftArgs i) (rightArgs i)) →
      DerivesEq formula (.app function leftArgs) (.app function rightArgs)

theorem DerivesEq.sound
    (satisfies : Satisfies interpretation formula)
    (derivation : DerivesEq formula left right) :
    interpretation.eval left = interpretation.eval right := by
  induction derivation with
  | refl => rfl
  | assumption member =>
      exact satisfies _ member
  | symm _ ih =>
      exact ih.symm
  | trans _ _ ih₁ ih₂ =>
      exact ih₁.trans ih₂
  | congr function related ih =>
      apply congrArg (interpretation.function function)
      funext i
      exact ih i

end EUF
